from langchain_openai import ChatOpenAI
from browser_use import Agent
import asyncio
import re
from dotenv import load_dotenv
load_dotenv()

async def main():
    # Accept user input for the task
    task = input("Specify the programming language and the problem for which the code snippet has to be generated by the agent AI: ")
    agent = Agent(
        task=task,
        llm=ChatOpenAI(model="gpt-4o"),
    )
    result = await agent.run()
     # Extract the Java code from the result
    final_result = result.final_result()
    print("Final Result:", final_result)
    code_match = re.search(r"```[a-zA-Z0-9_]+\n(.*?)\n```", final_result, re.DOTALL)
    code = code_match.group(1) if code_match else "No Java code found."
    print("Java Code:", code)
    # Save only the Java code to the file
    with open("output.txt", "w", encoding="utf-8") as file:
        file.write(code)
    

asyncio.run(main())